name: test-conan1
on:
    push:
    
jobs:
    conan1:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - run: |
                sudo apt update 
                sudo apt install -y gcc-12 cmake make  ninja-build libncurses5
                
            - run: sudo apt install clang-13 libc++abi-12-dev libc++-12-dev libstdc++-12-dev lld-13 llvm-13-dev llvm-13-linker-tools llvm clang

            - run: clang++-13 -v

            #- name: Install LLVM and Clang
            #  uses: KyleMayes/install-llvm-action@v2
            #  with:
            #    version: "13.0"
            #- name: Symlink libclang.so (Linux)
            #  if: contains(matrix.os, 'ubuntu')
            #  run: sudo ln -s libclang-11.so.1 /lib/x86_64-linux-gnu/libclang.so
            #  working-directory: ${{ env.LLVM_PATH }}/lib

            - run: pip3 install "conan<2"
            - run: conan profile new dummy
            - run: |
                cd recipes/cmaes/all
                cp profiles/clang-libc++-release ~/.conan/profiles
                conan create --profile clang-libc++-release . 0.10.0@

